name: Enviroments
on:
    workflow_dispatch:
        inputs:
            enviroment-name:
                type: environment
                default: test
                required: true
                description: Enviroment name
jobs:
    print:
        runs-on: ubuntu-latest
        environment: ${{ inputs.enviroment-name }}
        env:
            USERNAME: ${{ vars.USERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
        steps:
            - run: echo "${USERNAME}"
            - run: echo "${PASSWORD:0:1} ${PASSWORD#?}"